name: deploy-to-lightsail-server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      command: sudo docker compose exec --user=laradock -w /var/www/mid9songposts workspace
    steps:
    - name: ssh commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script_stop: true
        script: |
          cd ~/laradock
          ${{ env.command }} about

      
